### ISSUE TITLE
RetroScifiBlue not installing

### ISSUE THREAD

**Issue by Botspot** [phoenixbyrd/Screensavers#3]
I just ran a `git pull` on `/home/pi/Screensavers` to pull in your latest changes.

Running the install script for RetroScifiBlue did not work. I edited the script and removed the `clear` command in order for the errors to be visible.
Output:
```
pi@raspberrypi:~/Screensavers $ /home/pi/Screensavers/RetroScifiBlue/install.sh
cp: cannot stat 'RetroSciFi_Blue.scr': No such file or directory
cp: cannot stat 'Msvbvm60.dll': No such file or directory
cp: cannot stat 'screensaver.sh': No such file or directory
chmod: cannot access '/home/pi/.screensavers/screensaver.sh': No such file or directory
cp: cannot stat './fonts/*.TTF': No such file or directory
cp: cannot stat 'screensaver.service': No such file or directory
Failed to start screensaver.service: Unit screensaver.service not found.
Failed to enable unit: Unit file screensaver.service does not exist.
Box86 with Dynarec v0.2.1 5a0fbcd7 built on Apr 19 2021 12:45:51
Box86 with Dynarec v0.2.1 5a0fbcd7 built on Apr 19 2021 12:45:51
Box86 with Dynarec v0.2.1 5a0fbcd7 built on Apr 19 2021 12:45:51
wine: cannot find L"/home/pi/.screensavers/drive_c/windows/RetroSciFi_Blue.scr"
Reload service daemon      : sudo systemctl daemon-reload
Verify service is running  : sudo systemctl status screensaver
Enable on startup          : sudo systemctl enable screensaver
Start screensaver service  : sudo systemctl start screensaver
Stop screensaver service   : sudo systemctl stop screensaver
```

**Comment by Itai-Nelken** [comment]
I recommend to use `clear -x` in scripts, that way the text is pushed up but not deleted so its easier to debug errors but the output still looks nice.

**Comment by phoenixbyrd** [comment]
I removed everything I had installed, cloned the repo again but wasn't able to reproduce that exact error/issue. 

However, I did come across another issue where windows/fonts wasn't being picked up before the preview after install occurred and complained about missing fonts rather than starting the screensaver. 

Solution for that was to remove preview for these two after install.

I assume because of having messed with the installation of these before was why everything seemed to work properly and I had missed it.
